export const TASK_ACTIONS = {
  CREATE: 'CREATE',
  VIEW: 'VIEW',
  BACK: 'BACK',
  CLONE: 'CLONE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  ADJUST: 'ADJUST',
  COMPLETE: 'COMPLETE',
  COPY: 'COPY',
  RESET: 'RESET',
  CANCEL: 'CANCEL',
  UNLOCK: 'UNLOCK',
};
